### PR TITLE
Simplified undo commands due to simplification in engine.model.History.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Undo algorithms got simplified thanks to changes in `engine.model`: `History`, `RemoveOperation`, contextual OT.

### CODE REVIEW

**Comment by scofalik** [comment]
This PR depends on https://github.com/ckeditor/ckeditor5-engine/pull/977

**Comment by Reinmar** [comment]
Please resolve conflicts.

**Comment by Reinmar** [comment]
API docs need to be updated:

image

**Comment by scofalik** [comment]
Fixed.

**Pull request merged**
