### PR TITLE
T/ckeditor5 engine/1065 Tests: added integration tests.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Tests: added integration tests.

----

### Additional information

Apart of adding additional test I also refactored the whole suite so enabling plugins is easier.

### CODE REVIEW

**Comment by Reinmar** [comment]
Those tests are failing.

**Comment by scofalik** [comment]
Seems like fixed.

**Comment by Reinmar** [comment]
Sorry to say that – conflicts.

**Comment by scofalik** [comment]
Fixed

**Pull request merged**
